### ISSUE TITLE
integrated SDM predicts near-zeros across most of study area

### ISSUE THREAD

**Issue by jeffreyhanson** [iiasa/ibis.iSDM#102] opened 2024-03-11 02:06 UTC
Hi,

I've run into some unexpected behavior with the integrated INLA models, and I was hoping that you might have some advice? Although I first encountered this behaviour with the "real" dataset that I'm analyzing, I was able to reproduce this behavior with the built-in dataset too. Specifically, I can fit a species distribution model using INLA with presence/absence data and the predictions perfectly reasonble. However, when I try fitting a second model using INLA that also includes presence-only data, then I seem to only get predictions where either (1) all of the pixels are assigned a really small value (e.g. <1e-100), or (2) one pixel is assigned a really high value (e.g., >1e100) and every other pixel is assigned a really small value (e.g., <1e-100). I've tried playing around with changing the ratio of presence-only vs. presence vs. absence data, and this doesn't seem to make too much of a difference. Have you seen this behavior before?

I've included a reprex below (using the latest version in the master branch on GitHub). Please let me know if I can provide any further details?

```
# load packages
library(ibis.iSDM)
library(terra)
library(dplyr)

# set seed
set.seed(500)

# load data
bg_data <- 
  system.file("extdata/europegrid_50km.tif", package = "ibis.iSDM") |>
  terra::rast()
spp_data <- 
  system.file("extdata/input_data.gpkg", package = "ibis.iSDM") |>
  sf::read_sf()
env_data <- 
  system.file("extdata/predictors/", package = "ibis.iSDM") |>
  list.files("*.tif", full.names = TRUE) |>
  terra::rast()

# create absences
psa_sett <- 
  bg_data |>
  pseudoabs_settings(
    nrpoints = 50, 
    method = "mcp",
    inside = FALSE
  )
abs_data <- 
  spp_data |>
  add_pseudoabsence(field_occurrence = "Observed", settings = psa_sett) |>
  filter(type == "Pseudo-absence")

# create presence-only data
spp_data$pres_only <- 
  sample(c(TRUE, FALSE), size = nrow(spp_data), replace = TRUE)
pres_only_data <-
  spp_data |>
  filter(pres_only) |>
  select(-pres_only) |>
  slice_head(n = 50)

# create presence-absence data
pres_abs_data <-
  spp_data |>
  filter(!pres_only) |>
  select(-pres_only) |>
  slice_head(n = 50) |>
  bind_rows(abs_data)

# define model specification
## simple model fit with presence/absence data
model1 <- 
  distribution(bg_data) |>  
  add_predictors(env = env_data, transform = "scale", derivates = "none")  |> 
  add_biodiversity_poipa(pres_abs_data, field_occurrence = "Observed") |>  
  engine_inlabru()

## integrated model fit with presence/absence and presence-only data
model2 <- 
  distribution(bg_data) |>  
  add_predictors(env = env_data, transform = "scale", derivates = "none")  |> 
  add_biodiversity_poipo(pres_only_data, field_occurrence = "Observed") |>  
  add_biodiversity_poipa(pres_abs_data, field_occurrence = "Observed") |>  
  engine_inlabru()

# fit models
fit1 <- train(model1)
fit2 <- train(model2)

# extract raster
pred1 <- fit1$get_data()[[1]]
pred2 <- fit2$get_data()[[1]]

# visualize results
par(mfrow = c(1,2))
plot(pred1, main = "model with pres/abs data")
points(pres_abs_data |> filter(Observed > 0.5) |> vect(), col = "red")
points(pres_abs_data |> filter(Observed < 0.5) |> vect(), col = "blue")

plot(pred2, main = "integrated model")
points(pres_abs_data |> filter(Observed > 0.5) |> vect(), col = "red")
points(pres_only_data |> filter(Observed > 0.5) |> vect(), col = "orange")
points(pres_abs_data |> filter(Observed < 0.5) |> vect(), col = "blue")

```

![plot](https://github.com/iiasa/ibis.iSDM/assets/3610005/9031f0f1-653b-4792-a452-002cd1abea33)

## Session information

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /opt/R/R-4.3.1/lib/R/lib/libRblas.so 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Pacific/Auckland
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] terra_1.7-65    dplyr_1.1.4     ibis.iSDM_0.1.2

loaded via a namespace (and not attached):
 [1] Matrix_1.6-5        crayon_1.5.2        compiler_4.3.1     
 [4] renv_1.0.3          tidyselect_1.2.0    Rcpp_1.0.12        
 [7] MatrixModels_0.5-3  parallel_4.3.1      assertthat_0.2.1   
[10] splines_4.3.1       uuid_1.2-0          yaml_2.3.8         
[13] lattice_0.21-8      plyr_1.8.9          R6_2.5.1           
[16] generics_0.1.3      classInt_0.4-10     inlabru_2.10.1     
[19] sf_1.0-15           iterators_1.0.14    tibble_3.2.1       
[22] fmesher_0.1.5       units_0.8-5         stars_0.6-4        
[25] DBI_1.2.1           sn_2.1.1            pillar_1.9.0       
[28] rlang_1.1.3         utf8_1.2.4          sp_2.1-2           
[31] cli_3.6.2           withr_3.0.0         magrittr_2.0.3     
[34] class_7.3-22        foreach_1.5.2       grid_4.3.1         
[37] INLA_23.09.09       lifecycle_1.0.4     vctrs_0.6.5        
[40] mnormt_2.1.1        KernSmooth_2.23-21  proxy_0.4-27       
[43] glue_1.7.0          numDeriv_2016.8-1.1 codetools_0.2-19   
[46] stats4_4.3.1        abind_1.4-5         fansi_1.0.6        
[49] e1071_1.7-14        tools_4.3.1         pkgconfig_2.0.3 
```

**Comment by Martin-Jung** [comment] 2024-03-11 19:09
Hi,

thanks for reporting, but this is likely related to an erroneous model specification. I also note that the values are not 'near-zero' as implied by the issue title, but instead the colour ramp is highly skewed owing to a few positive outlier grid cells (which in turn are caused by a poorly optimized model).

Opposed to other engines INLA/INLABRU does not support any regularization thus one needs to be careful with the number of predictors as - across all datasets considered - the INLA optimizer tends have trouble with the solving with poorly covered variables (covered in terms of data spread across occurrence points). 
So if you run a `summary(fit2)` or `coef(fit2)` you will find a massive rather unstable coefficient for the variable `CLC3_335_mean_50km`. 

When removed 
`fit3 <- train(model2 |> rm_predictors('CLC3_335_mean_50km') )
plot(fit3)`
you are getting much more sensible results.

Another options could be to place strong (or any really) priors on your variables. For example if you don't want to exclude the variable in question this approach can help, by essentially putting a strong informative prior on 0 for the covariate in question.
```
pp <- priors(INLAPrior('CLC3_335_mean_50km',"norma", hyper = c(0, 1000)))
fit4 <- train(model2 |> add_priors(priors = pp) )
```
Alternatively one could a-priori select the variables better so as to avoid over-parametrization issues. This can be done manually (for example using a covariate selection routine on the variable set or via the options available via `train(..., filter_predictors = "none")`. For example
`fit5 <- train(model2, filter_predictors = "spear" )` or another method available there. This can in some cases work.

A last option could also be to 'clamp' the prediction directly.
Can be done to some level via `train(..., clamp = TRUE)` which limits the prediction to value ranges observed for the training data or rather hard-coded directly through a windsorization on the prediction.
So like this:
`pred2 <- predictor_transform(pred2, option = "windsor", windsor_props = c(0, 0.95))`

A last, but not recommended option could be to do a incremental variable selection via BIC. For INLABRU this can be turned on by checking `train(model2, optim_hyperparam = TRUE)` but this might take quite a while to fit :D 

Hope this helps. As you can see running a proper Inla iSDM is a pain in the butt :D 
I hope to have soon another integrated SDM engine available for the package....

**Comment by jeffreyhanson** [comment] 2024-03-11 22:02
Awesome - thank you very much for explaining all that! 

Yeah, you're right - I'm misreading the color  ramp - thanks for catching that.

Yeah, the tip about checking for unstable coefficients is really helpful. I'm currently playing around with including an extra variable selection step before model fitting that removes variables with low sd/variance at the sampled locations. Although removing highly correlated variables does help to some extent, I'm fitting distribution models for some rare species that don't have many observations and so just removing highly correlated variables still leaves in some variables with low sd/variance at sampled locations.

Also, I'm getting some warnings about using `train(..., clamp = TRUE)`. Specifically, the warning is:

```
Warning messages:
1: In pmax(pred[, v], vars_clamp$min[vars_clamp == v]) :
  an argument will be fractionally recycled
2: In pmin(pmax(pred[, v], vars_clamp$min[vars_clamp == v]), vars_clamp$max[vars_clamp ==  :
  an argument will be fractionally recycled
[these warnings are repeated a bunch of times]
```

Is it possible there might be a bug somewhere in the clamping code?

https://github.com/iiasa/ibis.iSDM/blob/8ce95a203d90fa9cfe2fa119a84b231ef18fa616/R/utils.R#L468-L472

Would something like this make more sense?

```
 for (v in intersect(vars_clamp$variable, names(pred))) {
    pred[, v] <- pmin(
      pmax(pred[, v], vars_clamp$min[vars_clamp$variable==v] ),
      vars_clamp$max[vars_clamp$variable==v])
  }
```

**Comment by jeffreyhanson** [comment] 2024-03-11 22:31
Hmm, playing around with the source code locally - fixing this bug seems to be a bit more complicated than originally anticipated.

**Comment by jeffreyhanson** [comment] 2024-03-11 22:51
I've just submitted a PR which seems to fix the issue

**Comment by Martin-Jung** [comment] 2024-03-21 09:19
Thanks for fixing. I have now also added a new engine to the `dev` branch, that `engine_scampr` that works at least with 2 datasets providing a relatively fast way for integration. It however does not support any weights as of yet, although one could think of hacking them into the quadrature exposure E (e.g. downweighting several presence points).

Will close this issue for now.

**Closed by Martin-Jung** 2024-03-21 09:19 UTC

**Comment by jeffreyhanson** [comment] 2024-03-21 19:52
Awesome - thank you! I'll check it out.
